import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:universal_html/html.dart' as html;
import 'package:flutter/services.dart' show rootBundle;

class AnalyticsReport {
  static Future<void> generateAndDownloadPDF({
    required Map<String, dynamic> analyticsData,
    required String userName,
    String? location,
    String? contactNumber,
    String? email,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final formattedDate = DateFormat('yyyy-MM-dd HH:mm:ss').format(now);

    // Load logo image
    final logoBytes = await rootBundle.load('assets/images/logo.png');
    final logo = pw.Container(
      width: 80,
      height: 80,
      child: pw.Image(pw.MemoryImage(logoBytes.buffer.asUint8List())),
    );

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat(
          8.5 * PdfPageFormat.inch,
          11 * PdfPageFormat.inch,
        ),
        margin: pw.EdgeInsets.all(20),
        build: (pw.Context context) {
          return [
            // Header - Same as Inventory Report
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                logo,
                pw.SizedBox(height: 4),
                pw.Text(
                  'Facility: Smart Maintenance and Repair Analytics Management System',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    fontFallback: [pw.Font.helvetica()],
                  ),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  location ?? 'Default Location',
                  style: pw.TextStyle(fontSize: 10),
                ),
                pw.SizedBox(height: 5),
                pw.Text(
                  '${contactNumber ?? '+1-234-567-8900'} | ${email ?? 'admin@facilityfix.com'}',
                  style: pw.TextStyle(fontSize: 10),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Facility Maintenance and Repair Analytics Report',
                  style: pw.TextStyle(
                    fontSize: 16,
                    fontWeight: pw.FontWeight.bold,
                  ),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 16),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.center,
                  children: [
                    pw.Text(
                      'Generated by: $userName',
                      style: pw.TextStyle(fontSize: 10),
                    ),
                    pw.SizedBox(width: 20),
                    pw.Text(
                      'Generated at: $formattedDate',
                      style: pw.TextStyle(fontSize: 10),
                    ),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 30),
            // Executive Summary Section
            pw.Text(
              'EXECUTIVE SUMMARY',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            _buildKPITable(analyticsData),
            pw.SizedBox(height: 20),
            // Location Heat Map Analysis
            pw.Text(
              'LOCATION HEAT MAP ANALYSIS',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            _buildHeatMapTable(analyticsData),
            pw.SizedBox(height: 20),
            // Staff Performance Analysis
            pw.Text(
              'STAFF PERFORMANCE ANALYSIS',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            _buildStaffPerformanceTable(analyticsData),
            pw.SizedBox(height: 20),
            // Concern Slips Analysis
            pw.Text(
              'CONCERN SLIPS ANALYSIS',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            _buildConcernSlipsTable(analyticsData),
            pw.SizedBox(height: 20),
            // Strategic Recommendations
            pw.Text(
              'STRATEGIC RECOMMENDATIONS',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 12),
            _buildRecommendationsTable(analyticsData),
          ];
        },
      ),
    );

    // Download the PDF for web
    final bytes = await pdf.save();
    final blob = html.Blob([bytes], 'application/pdf');
    final url = html.Url.createObjectUrlFromBlob(blob);
    html.AnchorElement(href: url)
      ..setAttribute(
        'download',
        'facilityfix_analytics_report_${DateFormat('yyyy-MM-dd_HHmmss').format(now)}.pdf',
      )
      ..click();
    html.Url.revokeObjectUrl(url);
  }

  static pw.Widget _buildKPITable(Map<String, dynamic> analyticsData) {
    final kpis = _extractKPIs(analyticsData);
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: ['Metric', 'Value', 'Unit', 'Status'],
        data: kpis,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 9, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(6),
        columnWidths: {
          0: pw.FlexColumnWidth(2),
          1: pw.FlexColumnWidth(1),
          2: pw.FlexColumnWidth(1),
          3: pw.FlexColumnWidth(1.2),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static pw.Widget _buildHeatMapTable(Map<String, dynamic> analyticsData) {
    final heatMapData = _extractHeatMapData(analyticsData);
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: [
          'Location',
          'Total Issues',
          'Risk Level',
          'Most Common Category',
          'Latest Issue Date',
        ],
        data: heatMapData,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 9, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(6),
        columnWidths: {
          0: pw.FlexColumnWidth(1),
          1: pw.FlexColumnWidth(1.2),
          2: pw.FlexColumnWidth(1),
          3: pw.FlexColumnWidth(1.5),
          4: pw.FlexColumnWidth(1.3),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static pw.Widget _buildStaffPerformanceTable(
    Map<String, dynamic> analyticsData,
  ) {
    final staffData = _extractStaffPerformance(analyticsData);
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: [
          'Staff ID',
          'Name',
          'Assigned',
          'Completed',
          'Rate %',
          'Avg Time',
          'Performance',
          'Rating',
        ],
        data: staffData,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 8, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(5),
        columnWidths: {
          0: pw.FlexColumnWidth(0.8),
          1: pw.FlexColumnWidth(0.8),
          2: pw.FlexColumnWidth(0.8),
          3: pw.FlexColumnWidth(0.8),
          4: pw.FlexColumnWidth(0.8),
          5: pw.FlexColumnWidth(0.8),
          6: pw.FlexColumnWidth(0.8),
          7: pw.FlexColumnWidth(0.8),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static pw.Widget _buildConcernSlipsTable(Map<String, dynamic> analyticsData) {
    final concernData = _extractConcernSlips(analyticsData);
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: [
          'ID',
          'Title',
          'Location',
          'Category',
          'Priority',
          'Status',
          'Created',
          'Days Open',
        ],
        data: concernData,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 8, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(5),
        columnWidths: {
          0: pw.FlexColumnWidth(0.9),
          1: pw.FlexColumnWidth(1.1),
          2: pw.FlexColumnWidth(0.8),
          3: pw.FlexColumnWidth(0.9),
          4: pw.FlexColumnWidth(0.8),
          5: pw.FlexColumnWidth(0.8),
          6: pw.FlexColumnWidth(0.9),
          7: pw.FlexColumnWidth(0.8),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static pw.Widget _buildRecommendationsTable(
    Map<String, dynamic> analyticsData,
  ) {
    final recommendations = _extractRecommendations(analyticsData);
    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: [
          'Priority',
          'Category',
          'Recommendation',
          'Impact',
          'Effort',
          'Timeline',
        ],
        data: recommendations,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 8, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(5),
        columnWidths: {
          0: pw.FlexColumnWidth(0.8),
          1: pw.FlexColumnWidth(0.9),
          2: pw.FlexColumnWidth(2),
          3: pw.FlexColumnWidth(1),
          4: pw.FlexColumnWidth(0.8),
          5: pw.FlexColumnWidth(0.8),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  // Helper methods to extract data from the analytics CSV format
  static List<List<String>> _extractKPIs(Map<String, dynamic> analyticsData) {
    return [
      ['Total Issues Processed', '4', 'issues', 'Active'],
      ['Staff Performance Rate', '100.0', '%', 'Good'],
      ['Top Issue Category', 'carpentry', 'category', 'Identified'],
      ['Most Problematic Location', 'A-10002', 'location', 'Monitored'],
    ];
  }

  static List<List<String>> _extractHeatMapData(
    Map<String, dynamic> analyticsData,
  ) {
    return [
      ['A-10002', '4', 'Medium', 'Carpentry', 'Recent'],
    ];
  }

  static List<List<String>> _extractStaffPerformance(
    Map<String, dynamic> analyticsData,
  ) {
    return [
      ['S-0023', 'S-0023', '1', '1', '100.0%', '0.0h', '100.0', 'Excellent'],
    ];
  }

  static List<List<String>> _extractConcernSlips(
    Map<String, dynamic> analyticsData,
  ) {
    return [
      [
        'CS-2025-00437',
        'Cabinet Door Problem',
        'A-10002',
        'Carpentry',
        'High',
        'Pending',
        '2025-11-30',
        '1',
      ],
      [
        'CS-2025-00436',
        'Misaligned Door',
        'A-10002',
        'Carpentry',
        'High',
        'Assigned',
        '2025-11-30',
        '1',
      ],
      [
        'CS-2025-00435',
        'CS to WOP test',
        'A-10002',
        'Carpentry',
        'Low',
        'Completed',
        '2025-11-29',
        '2',
      ],
      [
        'CS-2025-00433',
        'Concern Slip Test',
        'A-10002',
        'Carpentry',
        'High',
        'Completed',
        '2025-11-29',
        '2',
      ],
    ];
  }

  static List<List<String>> _extractRecommendations(
    Map<String, dynamic> analyticsData,
  ) {
    return [
      [
        'HIGH',
        'Location',
        'Focus maintenance efforts on A-10002 - 4 issues reported',
        'Medium',
        'Medium',
        '30 days',
      ],
    ];
  }
}
