import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';
import 'package:universal_html/html.dart' as html;
import 'package:flutter/services.dart' show rootBundle;

class InventoryReport {
  static Future<void> generateAndDownloadPDF({
    List<Map<String, dynamic>>? inventoryItems,
    required String userName,
    String? location,
    String? contactNumber,
    String? email,
  }) async {
    final pdf = pw.Document();

    // Use empty list if no items provided
    final items = inventoryItems ?? [];

    // Load logo image
    final logoBytes = await rootBundle.load('assets/images/logo.png');
    final logo = pw.Container(
      width: 80,
      height: 80,
      child: pw.Image(pw.MemoryImage(logoBytes.buffer.asUint8List())),
    );

    final now = DateTime.now();
    final formattedDate = DateFormat('yyyy-MM-dd HH:mm:ss').format(now);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat(8.5 * PdfPageFormat.inch, 11 * PdfPageFormat.inch),
        margin: pw.EdgeInsets.all(20),
        build: (pw.Context context) {
          return [
            // Header
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.center,
              children: [
                logo,
                pw.SizedBox(height: 4),
                pw.Text(
                  'Facility: Smart Maintenance and Repair Analytics Management System',
                  style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, fontFallback: [pw.Font.helvetica()]),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 10),
                pw.Text(
                  location ?? 'Location: Not Specified',
                  style: pw.TextStyle(fontSize: 10),
                ),
                pw.SizedBox(height: 5),
                pw.Text(
                  '${contactNumber ?? 'Contact: N/A'} | ${email ?? 'Email: N/A'}',
                  style: pw.TextStyle(fontSize: 10),
                ),
                pw.SizedBox(height: 8),
                pw.Text(
                  'Inventory and Procurement Reports',
                  style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold),
                  textAlign: pw.TextAlign.center,
                ),
                pw.SizedBox(height: 16),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.center,
                  children: [
                    pw.Text(
                      'Generated by: $userName',
                      style: pw.TextStyle(fontSize: 10),
                    ),
                    pw.SizedBox(width: 20),
                    pw.Text(
                      'Generated at: $formattedDate',
                      style: pw.TextStyle(fontSize: 10),
                    ),
                  ],
                ),
              ],
            ),
            pw.SizedBox(height: 30),
            // Enhanced Table
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400, width: 1),
                borderRadius: pw.BorderRadius.circular(4),
              ),
              child: pw.Table.fromTextArray(
                headers: ['Item No.', 'Item Name', 'Stock', 'Classification', 'Status'],
                data: items.map((item) => [
                  item['item_code'] ?? item['id'] ?? '',
                  item['item_name'] ?? '',
                  (item['current_stock'] ?? 0).toString(),
                  item['classification'] ?? item['category'] ?? 'General',
                  _getItemStatus(item),
                ]).toList(),
                headerStyle: pw.TextStyle(
                  fontWeight: pw.FontWeight.bold,
                  fontSize: 11,
                  color: PdfColors.white,
                ),
                headerDecoration: pw.BoxDecoration(
                  color: PdfColors.blue700,
                  borderRadius: pw.BorderRadius.only(
                    topLeft: pw.Radius.circular(4),
                    topRight: pw.Radius.circular(4),
                  ),
                ),
                cellStyle: pw.TextStyle(fontSize: 10, color: PdfColors.grey900),
                cellAlignment: pw.Alignment.topLeft,
                cellPadding: pw.EdgeInsets.all(8),
                columnWidths: {
                  0: pw.FlexColumnWidth(1.2),
                  1: pw.FlexColumnWidth(2.5),
                  2: pw.FlexColumnWidth(1),
                  3: pw.FlexColumnWidth(1.5),
                  4: pw.FlexColumnWidth(1.2),
                },
                border: pw.TableBorder(
                  bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                  left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                  right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
                ),
                tableWidth: pw.TableWidth.max,
                // Alternate row colors
                oddRowDecoration: pw.BoxDecoration(
                  color: PdfColors.grey50,
                ),
              ),
            ),
          ];
        },
      ),
    );

    // Download the PDF for web
    final bytes = await pdf.save();
    final blob = html.Blob([bytes], 'application/pdf');
    final url = html.Url.createObjectUrlFromBlob(blob);
    html.AnchorElement(href: url)
      ..setAttribute('download', 'inventory_report.pdf')
      ..click();
    html.Url.revokeObjectUrl(url);
  }

  static String _getItemStatus(Map<String, dynamic> item) {
    final currentStock = item['current_stock'] ?? 0;
    final reorderLevel = item['reorder_level'] ?? 0;

    if (currentStock == 0) {
      return 'Out of Stock';
    } else if (currentStock <= reorderLevel) {
      return 'Low Stock';
    } else {
      return 'In Stock';
    }
  }
}
