import 'dart:typed_data';

import 'package:pdf/widgets.dart' as pw;
import 'package:pdf/pdf.dart';
import 'package:flutter/services.dart' show rootBundle;
// Intl not required here; removed to avoid unused import

/// Utility to generate a PDF summary report for Work Orders.
///
/// Usage:
/// final bytes = await WorkOrderReport.generate(workOrders,
///   generatedBy: 'Admin User', generatedAt: DateTime.now());
/// Then save or print the returned `Uint8List` using `printing` or other APIs.
class WorkOrderReport {
  /// Generate PDF bytes from a list of work orders.
  /// Each work order is expected to be a map containing keys such as:
  /// `id`, `title`, `dateRequested`, `buildingUnit`, `priority`, `category`, `status`.
  static Future<Uint8List> generate(
    List<Map<String, dynamic>> workOrders, {
    String generatedBy = 'Admin User',
    DateTime? generatedAt,
    String facilityName =
        'Facility: Smart Maintenance and Repair Analytics Management System',
    String location = 'Default Location',
  }) async {
    final doc = pw.Document();

    generatedAt ??= DateTime.now();

    // Compute summary stats
    final total = workOrders.length;

    // Status breakdown
    final Map<String, int> statusCounts = {};
    final Map<String, int> priorityCounts = {};
    final Map<String, int> categoryCounts = {};
    final Set<String> uniqueLocations = {};
    int outstandingActions = 0;

    for (final w in workOrders) {
      final status = (w['status'] ?? 'pending').toString().toLowerCase();
      statusCounts[status] = (statusCounts[status] ?? 0) + 1;

      final priority = (w['priority'] ?? 'low').toString();
      priorityCounts[priority] = (priorityCounts[priority] ?? 0) + 1;

      final category = (w['category'] ?? 'uncategorized').toString();
      categoryCounts[category] = (categoryCounts[category] ?? 0) + 1;

      final bu = (w['buildingUnit'] ?? '').toString();
      if (bu.isNotEmpty) uniqueLocations.add(bu);

      // Consider pending/assigned/in_progress as requiring follow-up
      if ([
        'pending',
        'assigned',
        'in_progress',
        'to inspect',
        'to inspect',
      ].contains(status)) {
        outstandingActions += 1;
      }
    }

    // Load logo image
    final logoBytes = await rootBundle.load('assets/images/logo.png');
    final logo = pw.Container(
      width: 80,
      height: 80,
      child: pw.Image(pw.MemoryImage(logoBytes.buffer.asUint8List())),
    );

    // Layout: single page + table of details (may flow to another page)
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: pw.EdgeInsets.all(24),
        build: (context) {
          return [
            // Header
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Center(
                  child: pw.Column(
                    children: [
                      logo,
                      pw.SizedBox(height: 6),
                      pw.Text(
                        facilityName,
                        style: pw.TextStyle(
                          fontSize: 12,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(location, style: pw.TextStyle(fontSize: 10)),
                      pw.Text(
                        '+1-234-567-8900 | admin@facilityfix.com',
                        style: pw.TextStyle(fontSize: 10),
                      ),
                      pw.SizedBox(height: 8),
                      pw.Text(
                        'Work Order Summary Report',
                        style: pw.TextStyle(
                          fontSize: 18,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
                pw.SizedBox(height: 10),
                pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(
                      'Generated by: $generatedBy',
                      style: pw.TextStyle(fontSize: 9),
                    ),
                    pw.Text(
                      'Generated at: ${_formatDateTime(generatedAt!)}',
                      style: pw.TextStyle(fontSize: 9),
                    ),
                  ],
                ),
                pw.SizedBox(height: 12),
              ],
            ),

            // Summary box
            pw.Container(
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.blue300),
                color: PdfColors.blue50,
              ),
              padding: pw.EdgeInsets.all(12),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'SUMMARY SECTION',
                    style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.blue900,
                    ),
                  ),
                  pw.SizedBox(height: 6),
                  pw.Text(
                    'Total Number of Work Orders: $total',
                    style: pw.TextStyle(fontSize: 10),
                  ),
                  pw.Text('Date Range: N/A', style: pw.TextStyle(fontSize: 10)),
                  pw.Text(
                    'Location Coverage: ${uniqueLocations.length} unique building(s)/unit(s)',
                    style: pw.TextStyle(fontSize: 10),
                  ),
                  pw.Text(
                    'Outstanding Actions: $outstandingActions task(s) requiring follow-up',
                    style: pw.TextStyle(fontSize: 10),
                  ),
                ],
              ),
            ),

            pw.SizedBox(height: 12),

            // Status breakdown table
            pw.Text(
              'Task Status Breakdown',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            _buildKeyCountPercentageTable(statusCounts, total, [
              'Status',
              'Count',
              'Percentage',
            ]),

            pw.SizedBox(height: 10),

            // Priority distribution
            pw.Text(
              'Priority Distribution',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            _buildKeyCountPercentageTable(priorityCounts, total, [
              'Priority Level',
              'Count',
              'Percentage',
            ]),

            pw.SizedBox(height: 10),

            // Category overview
            pw.Text(
              'Category Overview',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 6),
            _buildKeyCountPercentageTable(categoryCounts, total, [
              'Category',
              'Count',
              'Percentage',
            ]),

            pw.SizedBox(height: 14),

            // Details header
            pw.Text(
              'WORK ORDER DETAILS',
              style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 8),

            // Details table
            _buildDetailsTable(workOrders),
          ];
        },
      ),
    );

    return doc.save();
  }

  static pw.Widget _buildKeyCountPercentageTable(
    Map<String, int> counts,
    int total,
    List<String> headers,
  ) {
    final rows = <List<String>>[];
    final sortedKeys = counts.keys.toList()..sort((a, b) => a.compareTo(b));
    for (final k in sortedKeys) {
      final c = counts[k] ?? 0;
      final p = total > 0 ? ((c / total) * 100) : 0.0;
      rows.add([k, c.toString(), '${p.toStringAsFixed(1)}%']);
    }

    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: headers,
        data: rows,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 9, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(6),
        columnWidths: {
          0: pw.FlexColumnWidth(1.5),
          1: pw.FlexColumnWidth(0.8),
          2: pw.FlexColumnWidth(1),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static pw.Widget _buildDetailsTable(List<Map<String, dynamic>> workOrders) {
    final headers = [
      'ID',
      'Title',
      'Date Requested',
      'Building & Unit',
      'Priority',
      'Category',
      'Status',
    ];

    final data =
        workOrders.map((w) {
          final id =
              (w['id'] ??
                      w['workOrderId'] ??
                      w['workOrder_id'] ??
                      w['work_order_id'] ??
                      '')
                  .toString();
          final title = (w['title'] ?? w['description'] ?? '').toString();
          final dateReq =
              (w['dateRequested'] != null)
                  ? _formatDate(w['dateRequested'])
                  : 'N/A';
          final bu =
              (w['buildingUnit'] ?? w['building'] ?? w['unit'] ?? '')
                  .toString();
          final priority = (w['priority'] ?? '').toString();
          final category = (w['category'] ?? '').toString();
          final status = (w['status'] ?? '').toString();
          return [id, title, dateReq, bu, priority, category, status];
        }).toList();

    return pw.Container(
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400, width: 1),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Table.fromTextArray(
        headers: headers,
        data: data,
        headerStyle: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 9,
          color: PdfColors.white,
        ),
        headerDecoration: pw.BoxDecoration(
          color: PdfColors.blue700,
          borderRadius: pw.BorderRadius.only(
            topLeft: pw.Radius.circular(4),
            topRight: pw.Radius.circular(4),
          ),
        ),
        cellStyle: pw.TextStyle(fontSize: 9, color: PdfColors.grey900),
        cellAlignment: pw.Alignment.topLeft,
        cellPadding: pw.EdgeInsets.all(6),
        columnWidths: {
          0: pw.FlexColumnWidth(1),
          1: pw.FlexColumnWidth(3),
          2: pw.FlexColumnWidth(1.5),
          3: pw.FlexColumnWidth(1.5),
          4: pw.FlexColumnWidth(1),
          5: pw.FlexColumnWidth(1.5),
          6: pw.FlexColumnWidth(1),
        },
        border: pw.TableBorder(
          bottom: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          left: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
          right: pw.BorderSide(color: PdfColors.grey300, width: 0.5),
        ),
        tableWidth: pw.TableWidth.max,
        oddRowDecoration: pw.BoxDecoration(color: PdfColors.grey50),
      ),
    );
  }

  static String _formatDate(dynamic date) {
    if (date == null) return 'N/A';
    try {
      DateTime dt;
      if (date is String)
        dt = DateTime.parse(date);
      else if (date is DateTime)
        dt = date;
      else
        return 'N/A';
      return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';
    } catch (_) {
      return 'N/A';
    }
  }

  static String _formatDateTime(DateTime dt) {
    return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')} ${dt.hour.toString().padLeft(2, '0')}:${dt.minute.toString().padLeft(2, '0')}:${dt.second.toString().padLeft(2, '0')}';
  }
}
