// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    authDomain: 'facilityfix-6d27a.firebaseapp.com',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    messagingSenderId: '495669461131',
    appId: '1:495669461131:web:4468207a00c965a2a7548e',
    measurementId: 'G-CTYHR31S0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    appId: '1:495669461131:android:7e8a9b6c5d4e3f2a1b9c8d',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    appId: '1:495669461131:ios:7e8a9b6c5d4e3f2a1b9c8d',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    iosBundleId: 'com.example.facilityfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    appId: '1:495669461131:macos:7e8a9b6c5d4e3f2a1b9c8d',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    iosBundleId: 'com.example.facilityfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBIQwgUZlxDSHV8-v78VJ6UOASBx0l6OU',
    appId: '1:495669461131:windows:7e8a9b6c5d4e3f2a1b9c8d',
    messagingSenderId: '495669461131',
    projectId: 'facilityfix-6d27a',
    authDomain: 'facilityfix-6d27a.firebaseapp.com',
    storageBucket: 'facilityfix-6d27a.firebasestorage.app',
    measurementId: 'G-CTYHR31S0Q',
  );
}
