// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDH_3YyGzT6XwQx1VGJjMQn4_yKJb1234', // Replace with your actual API key
    authDomain: 'facilityfix-project.firebaseapp.com', // Replace with your auth domain
    projectId: 'facilityfix-project', // Replace with your project ID
    storageBucket: 'facilityfix-project.appspot.com', // Replace with your storage bucket
    messagingSenderId: '123456789012', // Replace with your sender ID
    appId: '1:123456789012:web:abcdef1234567890', // Replace with your app ID
    measurementId: 'G-XXXXXXXXXX', // Optional: Replace with your measurement ID
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDH_3YyGzT6XwQx1VGJjMQn4_yKJb1234',
    appId: '1:123456789012:android:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'facilityfix-project',
    storageBucket: 'facilityfix-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDH_3YyGzT6XwQx1VGJjMQn4_yKJb1234',
    appId: '1:123456789012:ios:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'facilityfix-project',
    storageBucket: 'facilityfix-project.appspot.com',
    iosBundleId: 'com.example.facilityfix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDH_3YyGzT6XwQx1VGJjMQn4_yKJb1234',
    appId: '1:123456789012:macos:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'facilityfix-project',
    storageBucket: 'facilityfix-project.appspot.com',
    iosBundleId: 'com.example.facilityfix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDH_3YyGzT6XwQx1VGJjMQn4_yKJb1234',
    appId: '1:123456789012:windows:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'facilityfix-project',
    authDomain: 'facilityfix-project.firebaseapp.com',
    storageBucket: 'facilityfix-project.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}
